server:
  port: 8100
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: swagger
          uri: lb://GATEWAY-SERVICE
          order: 1000
          predicates:
            - Path=/api/**
          filters:
            - SwaggerHeaderFilter
        - id: pokemon-service
          uri: lb://POKEMON-SERVICE
          predicates:
            - Path=/pokemon-service/**
          filters:
            - StripPrefix=1

        - id: gym-service
          uri: lb://GYM-SERVICE
          predicates:
            - Path=/gym-service/**
          filters:
            - StripPrefix=1

      # Without specifying routes, would have to prefix with eureka service name (case-sensitive) when calling APIs
      ## e.g.: localhost:8100/<eureka-service-name>/<endpoint exposed by the eureka service name that we want to call>
      ## this would also resulted in ReactiveCompositeDiscoveryClients to be detected - need to find how to explicitly disable spring.cloud.discovery.reactive.clients
      discovery:
        locator:
          enabled: false

