server:
  port: 8100
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/gateway-service
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: app
            client-secret: 83696c0f-f76c-4b4c-b4fc-47800b22eb3e
  cloud:
    gateway:
      routes:
        - id: swagger
          uri: lb://GATEWAY-SERVICE
          order: 1000
          predicates:
            - Path=/api/**
          filters:
            - TokenRelay=
#            - SwaggerHeaderFilter
        - id: openapi
          uri: http://localhost:8100
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: pokemon-service
          uri: lb://POKEMON-SERVICE
          predicates:
          - Path=/pokemon-service/**
          filters:
#            - StripPrefix=1
          - RewritePath=/pokemon-service/(?<path>.*), /$\{path}
#            - TokenRelay=
        - id: gym-service
          uri: lb://GYM-SERVICE
          predicates:
            - Path=/gym-service/**
          filters:
            - StripPrefix=1

      # Without specifying routes, would have to prefix with eureka service name (case-sensitive) when calling APIs
      ## e.g.: localhost:8100/<eureka-service-name>/<endpoint exposed by the eureka service name that we want to call>
      ## this would also resulted in ReactiveCompositeDiscoveryClients to be detected - need to find how to explicitly disable spring.cloud.discovery.reactive.clients
      discovery:
        locator:
          enabled: true
springdoc:
  api-docs:
    groups:
      enabled: true

#
#keycloak:
#  auth-server-url: http://localhost:8080/auth
#  realm: app
#  #  public-client: true
#  principal-attribute: preferred_username
#  resource: app
#  credentials:
#    secret: 634fed40-5c00-4924-b704-04de370ba446
#  use-resource-role-mappings: true
#  autodetect-bearer-only: true
#  security-constraints:
#    - auth-roles:
#        - Apple
#      security-collections:
#        - name:
#          patterns:
#            - /item/*

