server:
  port: 8100
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: openfeign
          uri: lb://OPENFEIGN
          predicates:
            - Path=/**
