server:
  port: 8100
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
#            issuer-uri: http://localhost:8080/auth/realms/gateway-service
            issuer-uri: http://192.168.99.102:31335/auth/realms/my-gateway
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: app
            client-secret: fb6403df-ea17-4e13-953a-c6ab109f0217
#            client-secret: 83696c0f-f76c-4b4c-b4fc-47800b22eb3e
  cloud:
    gateway:
      routes:
        - id: swagger
#          uri: http://localhost:8100
          uri: http://spring-gateway123.com
          order: 1000
          predicates:
            - Path=/api/**
          filters:
            - SwaggerHeaderFilter
#            - TokenRelay=
        - id: openapi
#          uri: http://localhost:8100
          uri: http://spring-gateway123.com
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - SwaggerHeaderFilter
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
        - id: pokemon-service
#          uri: http://openfeign:8001
          uri: http://openfeign123.com
          predicates:
           - Path=/pokemon-service/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1

      # Without specifying routes, would have to prefix with eureka service name (case-sensitive) when calling APIs
      ## e.g.: localhost:8100/<eureka-service-name>/<endpoint exposed by the eureka service name that we want to call>
      ## this would also resulted in ReactiveCompositeDiscoveryClients to be detected - need to find how to explicitly disable spring.cloud.discovery.reactive.clients
springdoc:
  api-docs:
    groups:
      enabled: true

#
#keycloak:
#  auth-server-url: http://localhost:8080/auth
#  realm: app
#  #  public-client: true
#  principal-attribute: preferred_username
#  resource: app
#  credentials:
#    secret: 634fed40-5c00-4924-b704-04de370ba446
#  use-resource-role-mappings: true
#  autodetect-bearer-only: true
#  security-constraints:
#    - auth-roles:
#        - Apple
#      security-collections:
#        - name:
#          patterns:
#            - /item/*

